server:
  servlet:
    context-path: /api/costumer
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
data:s
mongodb:
uri: mongodb://localhost/test